### ISSUE TITLE
Not translating texts with periods

### ISSUE THREAD

**Issue by alvarotrigo** [claudetech/node-static-i18n#11]
For example:

```html
<p data-t>This is a demo of a text that won't get translated. Not sure why.</p>
```

Using the following json file:

```json
{
  "Create": "pepe",
  "This is a demo of a text that won't get translated. Not sure why.": "aaaaa"
}
```

It seems the dot is not allowed within the key. Not matter if you use json or yaml

**Comment by alvarotrigo** [comment]
Found the solution, we have to change the default value for `keyseparator` in i18nnext

```shell
static-i18n -l en -i en -i es --fileFormat yml --i18n "{\"keyseparator\": \"::\"}" www
```

**Comment by tuvistavie** [comment]
Hi.
Yes, by default `.` is used to separate keys to be able to nest them.
As you said, changing the keyseparator is I think the best solution.

Note that you can used single quotes in your shell to avoid having to escape JSON keys:

```
static-i18n -l en -i en -i es --fileFormat yml --i18n '{"keyseparator": "::"}' www
```
