### ISSUE TITLE
Configure i18n options

### ISSUE THREAD

**Issue by alvarotrigo** [claudetech/node-static-i18n#12]
Not clear in the docs, it says:

> i18n: Object passed directly to i18next.init. This allows you to override pretty much anything. Read i18next doc for more info.
> When using the CLI, outputOverride and i18n options are parsed as JSON.

I'm trying the following without success:

> static-i18n -l en -i en -i es --fileFormat yml --i18n {"nsseparator": ":::", "keyseparator": "::"} www

Getting: 

> static-i18n [options] directory

**Comment by alvarotrigo** [comment]
Apparently we have to escape the string:

```shell
static-i18n -l en -i en -i es --fileFormat yml --i18n "{\"keyseparator\": \"::\"}" www
```

**Comment by tuvistavie** [comment]
The behavior is shell dependent, but as I mentioned in another issue, using single quotes should avoid escaping:

```
static-i18n -l en -i en -i es --fileFormat yml --i18n '{"keyseparator": "::"}' www
```

**Comment by alvarotrigo** [comment]
Thanks for that!
