### ISSUE TITLE
interpolation is not working on <title> tag

### ISSUE THREAD

**Issue by cmdesign85** [claudetech/node-static-i18n#13]
Hi,

I succeed in making translation and interpolation work perfectly. I succeed in translate <title> tag, but as soon as I use interpolation, the translation stop working.
This works (no interpolation): 
`<title data-t="main.chapter"></title>`
`<title data-t>main.chapter</title>`
This doesn't work (with interpolation) : 
`<title data-attr-t data-attr-t-interpolate data-t="{{main.chapter}}1"></title>`
`<title data-attr-t data-attr-t-interpolate data-t>{{main.chapter}}1</title>`

Interpolation works fine in the rest of the page.

**Comment by tuvistavie** [comment]
Thanks for reporting, it should now be fixed.
Thanks to @alvarotrigo, you should also now be able to write

```
<title data-t data-t-interpolate>{{main.chapter}} 1</title>
```

**Comment by cmdesign85** [comment]
Thanks,
I tried `npm update -g static-i18n` and `npm update static-i18n` but nothings seems to work and the interpolation still doesn't work. How do I make the update ?

**Comment by alvarotrigo** [comment]
@tuvistavie did you push the changes to npm? I think you might need to create a new release here on github, then use `npm publish`.
