### ISSUE TITLE
Translate text without wrapper 

### ISSUE THREAD

**Issue by alvarotrigo** [claudetech/node-static-i18n#14]
Having something like:

```html
<div class="demo">
    <div class="loading"></div>
    My text here 
</div>
```

There's no easy way to translate the text "My text here" unless wrapped in a some kind of element.

Something similar occurs when using other frameworks such as Knockout.js, but the solution they adopted was allowing the use of HTML comments for those cases, so it would end up like this:

```html
<div class="demo">
    <div class="loading"></div>
    <!-- data-t-->My text here<!-- -->
</div>
```

A solution like this would be great for this module. 
As far as I know I didn't find an easy way of dealing with theses cases. Correct me if I'm wrong.

**Comment by alvarotrigo** [comment]
I thought about using interpolation but noticed it only works for attributes?
Was thinking of doing something like this:

```html 
<div class="demo" data-t-interpolate>
    <div class="loading"></div>
    {{My text here}}
</div>
```

**Comment by tuvistavie** [comment]
I think this should be fixed by your PR too, thanks.

**Comment by cmdesign85** [comment]
You can also put a <span data-t>your text</span> around your text. I use it a lot, it works perfectly.
