### ISSUE TITLE
Not translating texts with indendation

### ISSUE THREAD

**Issue by alvarotrigo** [claudetech/node-static-i18n#15]
It is quite common to have HTML code structured with indendation of some kind, tabs, spaces...
Having something like this won't get translated due to the indendation:

```html
<div data-t>
    Extensions
</div>
```

It seems it requires it in a single line and without indent:
```html
<div data-t>Extensions</div>
```

Perhaps using something like this could make things easier:

```html
<div data-t>
    {{Extensions}}
</div>
```
Which at the moment doesn't work but that would be very similar to the current use of interpolation ?

**Comment by tuvistavie** [comment]
I suppose this should be fixed thanks to your PR, thanks.
