### ISSUE TITLE
img and input tag not closed correctly

### ISSUE THREAD

**Issue by fcbflying** [claudetech/node-static-i18n#34]
Hi, it seems the img and input tag are not closed correctly.
This is my Example:
`
<input type="text" name="age" value="12"/>
<img src="images/test.jpg" alt="test image"/>`

And the output:
`<input type="text" name="age" value="12">
<img src="images/test.jpg" alt="test image">`

After i18n compilation, their closing slash "/"  are lost.

**Comment by danhper** [comment]
This is the expected behavior. There is a `xml` option which can be set to true if you want to have self-closing tags.
