### ISSUE TITLE
A single --exclude 'filename_to_exclude' flag results in every character being checked instead of the whole filename

### ISSUE THREAD

**Issue by henriheimann** [claudetech/node-static-i18n#42]
When calling static-i18n with a single `--exclude 'filename_to_exclude'` flag, every file whose name includes a single character of 'filename_to_exclude' is excluded instead of files whose name starts with 'filename_to_exclude'.

**Comment by danhper** [comment]
Hi and sorry for the delay.
`exclude` was indeed not cast properly to an array. This should now be fixed, thanks for reporting!
