### ISSUE TITLE
Feature request: Translate only part of a custom attribute

### ISSUE THREAD

**Issue by harley01** [claudetech/node-static-i18n#5]
This project is really great, thank you!
I use it to generate my entire website statically. 

I have a feature request, if I may.
_Can the custom attributes be allowed to have only a part of their value translated?_

For example, given this code:
`<link rel="canonical" data-attr-t href-t="links.baseAbsolute/fileName" />`

I need just the links.baseAbsolute part to be translated and leave the rest of the value as is.
For example if links.baseAbsolute is https://www.example.com then it should do this:

`<link rel="canonical" data-attr-t href-t="https://www.example.com/fileName" />`

My proposal to use this feature would look something like this:
`<link rel="canonical" data-attr-t href-t="{{links.baseAbsolute}}/fileName" />`

It should parse just the parts wrapped in {{ }} and translate them, leaving the rest intact.

Please let me know if this doesn't make any sense.

**Comment by tuvistavie** [comment]
Hi, thanks for the idea.
I agree this could be useful, but as is, it would be a breaking change, which I would like to avoid.
We could add a new option to enable/disable this feature, but as I think that it would not be something we want all the time, what about having an attribute controlling the syntax of translated attributes?
For example, adding `data-attr-t-interpolate` could activate the feature on the current tag.

```html
<link rel="canonical" data-attr-t data-attr-t-interpolate href-t="{{links.baseAbsolute}}/fileName" />
```

What do you think?

**Comment by harley01** [comment]
Looks great!

**Comment by tuvistavie** [comment]
Ok, let's go with this approach then!
I don't have a lot of time right now and am not sure how soon I will be able to get this implemented, do you think you would have the time to send a PR for this?
Thank you!

**Comment by harley01** [comment]
Yes, leave it with me.

**Comment by tuvistavie** [comment]
Thank you very much, I will be looking forward to your PR then :smiley:

**Comment by tuvistavie** [comment]
I just published a new version to npm, thank you very much :smiley:

**Comment by harley01** [comment]
Great, thanks!
