### ISSUE TITLE
Error Debug

### ISSUE THREAD

**Issue by tanzaho** [claudetech/node-static-i18n#7]
Hi,

I just faced an issue where the translation just stopped working. Is there any way to show error logs when that happens ?

**Comment by tuvistavie** [comment]
Hi, thanks for reporting.
If an error occurs, it should be reported to stdout.
Would you have a minimal example to reproduce?
Thank you!

**Comment by tanzaho** [comment]
Yes, any malformed JSON input:

```
{
  "my": {
    "key": "Salut"
  },
  "other": {
    "key": "mec",
    "ok": "confirmer",
  }
}
```

**Comment by tuvistavie** [comment]
Oh, I see, I'll take a look, thank you!
Of course if you have time, PRs are very welcome!
