### ISSUE TITLE
Where to configure it?

### ISSUE THREAD

**Issue by alvarotrigo** [claudetech/node-static-i18n#9]
The docs don't state where we should configure the module, just the [configuration options](https://github.com/claudetech/node-static-i18n#configuration).

It might be a lame question but... I'm just not used to work on node :) 

And example would come on handy.

The console only outputs:

> usage: static-i18n [options] directory

But doesn't state in which format we should pass the options. 

> static-i18n -l en -i en -i es fileFormat: yaml www?
> static-i18n -l en -i en -i es -fileFormat: yaml www? 
> static-i18n -l en -i en -i es -fileFormat yaml www

**Comment by orjandh** [comment]
Took me some time to figure out, but you can use the -t option in CLI to pass fileFormat.

https://github.com/claudetech/node-static-i18n/blob/master/bin/static-i18n.js#L29
